### ISSUE TITLE
.ICS instead of Google Calendar

### ISSUE THREAD

**Issue by lorddusk** [AyronK/arpg-timeline#56] opened 2024-07-07 16:47 UTC
**Is your feature request related to a problem? Please describe.**
Not everyone uses google calendar, swapping it out for a .ics file makes it compatible with (almost) all calendars people are using.

**Describe the solution you'd like**
Instead of a link to create a google calendar entry, make it download an .ics file that you can open in your preferred calendar app.

**Comment by AyronK** [comment] 2024-07-07 17:13
That's nearly a duplicate of #9. I'll mention your suggestion there

**Closed by AyronK** 2024-07-07 17:13 UTC
